// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * Use this data source to access information about existing resources.
 */
export function getResources(args?: GetResourcesArgs, opts?: pulumi.InvokeOptions): Promise<GetResourcesResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("azure:core/getResources:getResources", {
        "location": args.location,
        "managementGroupIds": args.managementGroupIds,
        "name": args.name,
        "requiredTags": args.requiredTags,
        "resourceGroupName": args.resourceGroupName,
        "subscriptionIds": args.subscriptionIds,
        "type": args.type,
    }, opts);
}

/**
 * A collection of arguments for invoking getResources.
 */
export interface GetResourcesArgs {
    /**
     * Only return resources that deployed at a specific location
     */
    location?: string;
    managementGroupIds?: string[];
    /**
     * The name of the Resource to search for
     */
    name?: string;
    requiredTags?: {[key: string]: string};
    /**
     * The name of the Resource group where the Resources are located
     */
    resourceGroupName?: string;
    subscriptionIds?: string[];
    /**
     * The Resource Type of the Resources you want to list
     */
    type?: string;
}

export interface GetResourcesResult {
    readonly resources: outputs.core.GetResourcesResource[];
}
/**
 * Use this data source to access information about existing resources.
 */
export function getResourcesOutput(args?: GetResourcesOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetResourcesResult> {
    return pulumi.output(args).apply((a: any) => getResources(a, opts))
}

/**
 * A collection of arguments for invoking getResources.
 */
export interface GetResourcesOutputArgs {
    /**
     * Only return resources that deployed at a specific location
     */
    location?: pulumi.Input<string>;
    managementGroupIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The name of the Resource to search for
     */
    name?: pulumi.Input<string>;
    requiredTags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The name of the Resource group where the Resources are located
     */
    resourceGroupName?: pulumi.Input<string>;
    subscriptionIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The Resource Type of the Resources you want to list
     */
    type?: pulumi.Input<string>;
}
